### ISSUE TITLE
Clean up before freeze

### ISSUE THREAD

**Issue by karlfloersch** [ethereum-optimism/contracts-v2#4]
## TODO
- [x] Rename / update transaction types
- [ ] Rename native transaction
- [x] Fix Ring Buffer
- [x] Integrate optimized merkle tree
- [x] Test multi-batch submission 
- [x] Implement efficient multi-batch submission encoding [Karl - in prog]

### Rename / update transaction types
Transaction type includes `number` -- is this block number? If it is `tx index` then we should call it `txIndex` but if it's block number we should either call it `blockNumber`, or (my preference) call timestamp and blockNumber `lastL1Timestamp` and `lastL1BlockNumber` to avoid confusion -- https://github.com/ethereum-optimism/contracts-v2/blob/feat/polish/contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol#L73-L81

### Rename native transaction
Replace "native" transaction here https://github.com/ethereum-optimism/contracts-v2/blob/feat/polish/contracts/optimistic-ethereum/libraries/codec/Lib_OVMCodec.sol#L31 with EIP155 transaction

### Fix Ring Buffer
Our current ring buffer is not correctly implemented & has weird edge cases where garbage collection is not handled correctly.

###  Integrate optimized merkle tree 
We've got to integrate the optimized merkle tree -- https://github.com/ethereum-optimism/contracts-v2/blob/feat/polish/contracts/optimistic-ethereum/libraries/utils/Lib_MerkleUtils.sol#L9

**Comment by kfichter** [comment]
Closing old issues
